### ISSUE TITLE
v4.1.0 does not handle relative inputs

### ISSUE THREAD

**Issue by Turbo87** [chadhietala/broccoli-rollup#52] opened 2019-05-17 06:37 UTC
We just tried to update from v4.0.0 to v4.1.0 and for some reason the new version seems to cause build failures:

```
ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'

=================================================================================

ENV Summary:

  TIME: Thu May 16 2019 20:52:51 GMT+0000 (Coordinated Universal Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /builds/qonto/qonto-js/node_modules/.bin/ember
  - exam
  - --split=8
  - --parallel
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1558039840911-0.3519560502598835
  - /builds/qonto/qonto-js/node_modules/.bin
  - /usr/local/share/.config/yarn/link/node_modules/.bin
  - /builds/qonto/qonto-js/node_modules/.bin
  - /usr/local/share/.config/yarn/link/node_modules/.bin
  - /usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/local/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/local/bin/node_modules/npm/bin/node-gyp-bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  PLATFORM: linux x64
  FREEMEM: 8970514432
  TOTALMEM: 15768760320
  UPTIME: 373
  LOADAVG: 1.92578125,1.4169921875,0.6416015625
  CPUS:
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  - Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.3
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.51
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
    at Object.realpathSync (fs.js:1456:7)
    at _walkSync (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/walk-sync/index.js:101:23)
    at Function.entries (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/walk-sync/index.js:34:16)
    at Object.treeFromPath (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/utils.js:81:37)
    at RollupHelper.syncInput (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/rollup-helper.js:36:39)
    at RollupHelper.build (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/rollup-helper.js:23:32)
    at BroccoliRollup.build (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/index.js:42:32)
    at resolve (/builds/qonto/qonto-js/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/builds/qonto/qonto-js/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/builds/qonto/qonto-js/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
  - errorMessage: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
        at BroccoliRollup
-~- created here: -~-
    at new Plugin (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/broccoli-plugin/index.js:30:32)
    at new BroccoliRollup (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/index.js:14:9)
    at module.exports (/builds/qonto/qonto-js/ember-cli-build.js:67:23)
    at Builder.readBuildFile (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:31:10)
    at BuildTask.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
        at BroccoliRollup
-~- created here: -~-
    at new Plugin (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/broccoli-plugin/index.js:30:32)
    at new BroccoliRollup (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/index.js:14:9)
    at module.exports (/builds/qonto/qonto-js/ember-cli-build.js:67:23)
    at Builder.readBuildFile (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:31:10)
    at BuildTask.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: BroccoliRollup
  - originalErrorMessage: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
  - stack: Error: ENOENT: no such file or directory, lstat '/tmp/broccoli-1713V9oMBA72T6h/cache-900-broccoli_rollup/build/lib'
    at Object.realpathSync (fs.js:1456:7)
    at _walkSync (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/walk-sync/index.js:101:23)
    at Function.entries (/builds/qonto/qonto-js/node_modules/broccoli-rollup/node_modules/walk-sync/index.js:34:16)
    at Object.treeFromPath (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/utils.js:81:37)
    at RollupHelper.syncInput (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/rollup-helper.js:36:39)
    at RollupHelper.build (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/rollup-helper.js:23:32)
    at BroccoliRollup.build (/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/index.js:42:32)
    at resolve (/builds/qonto/qonto-js/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/builds/qonto/qonto-js/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/builds/qonto/qonto-js/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

We use it roughly like this:

```js
  let fooTree = new Rollup('lib', {
    rollup: {
      input: 'foo.js',
      output: {
        file: 'assets/foo.js',
        format: 'iife',
      },
      plugins: [resolve(), commonjs()],
    },
  });
```

**Comment by samselikoff** [comment] 2019-05-17 11:51
Same: https://travis-ci.org/embermap/ember-cli-tailwind/jobs/533661863

Usage is [here](https://github.com/embermap/ember-cli-tailwind/blob/889bb8e1a914fc38a552401332c86d1d619fabf5/lib/build-tailwind.js#L25):

```js
let tailwindConfigTree = new Rollup(inputPath, {
  rollup: {
    input: 'config/tailwind.js',
    output: {
      file: 'tailwind-config.js',
      format: 'cjs'
    },
    plugins: [
      resolve(),
      commonjs()
    ]
  }
});
```

**Comment by krisselden** [comment] 2019-05-20 07:45
The issue is I'm using the build's watchedFiles to determine if the input affected the build to avoid rebuilding when no input changed but I didn't realize that plugins will sometimes add dependencies that aren't actually files https://github.com/rollup/rollup/blob/0655489c532ed78a59175ca87b1fd6af68062acc/src/watch/fileWatchers.ts#L55

I need to check for ENOENT and ignore it.

**Comment by krisselden** [comment] 2019-05-20 08:09
Though it seems like the convention for a plugin to add a resolved dep id that isn't an actually file is to prefix it with '\0' which just checking for that fixes tailwind issue.
https://github.com/rollup/rollup/blob/master/src/ModuleLoader.ts#L56

@Turbo87 The above commentary is for @samselikoff issue which judging by your stacktrace is not the same issue.  I have no idea how to reproduce your issue nor what the issue is. It is happening in require('walk-sync').entries(path) of the node.inputPaths[0], I did update the walk-sync node module which did include resolving symlinks to detect symlink cycles which seems like it could be related.

**Comment by Turbo87** [comment] 2019-05-20 08:32
@krisselden we essentially have a JS file in a folder called `lib`, that imports a module from `node_modules` and exports a wrapper function. we use `return app.toTree([fooTree]);` in the `ember-cli-build.js` file to build that with Rollup as part of the regular app build.

**Comment by rwjblue** [comment] 2019-05-20 15:52
@Turbo87 - Can you:

* work up a repro that we can dig into?
* see what the contents of [this path](https://github.com/chadhietala/broccoli-rollup/blob/f4cfd8f6da032e3280d47e75bcf2828cc5612539/src/utils.ts#L112) is when it blows up?

**Comment by rwjblue** [comment] 2019-05-20 15:59
Also, its not clear if the reported errors are for the first build or for rebuilds

**Comment by Turbo87** [comment] 2019-05-20 16:27
It was for the first build already. I'm currently on vacation, I can work on the repro once I'm back (two weeks).

**Comment by krisselden** [comment] 2019-05-20 16:41
@Turbo87 I do have tests that "essentially" do that.  The stack trace does not lead me to believe it is as straightforward to reproduce as you believe it to be.  I need an actual reduced reproduction.

The stacktrace points to failing at `/builds/qonto/qonto-js/node_modules/broccoli-rollup/dist/rollup-helper.js:36:39` which maps to https://github.com/chadhietala/broccoli-rollup/blob/master/src/rollup-helper.ts#L50 and inputPath in this case is `inputPaths[0]` on the broccoli node. `treeFromPath(inputPath)` in turn just calls `walkSync.entries(inputPath)`. 

walk-sync was bumped in 4.0.0 not 4.1.0.  And for a long time broccoli-rollup has started with walkSync inputPaths[0]
https://github.com/chadhietala/broccoli-rollup/blob/8d44c4d7c93e3adbd196ccdc0a37ed8eea9c8873/index.ts#L102

**Comment by rwjblue** [comment] 2019-05-20 17:04
I think this may be very _specifically_ due to using a relative string directory. We'd need to dig into it to confirm, but in v4.1.0 we now `process.chdir` _before_ creating the input tree to be synced. I was under the impression that Broccoli itself resolved the paths to absolute before setting `this.inputPaths`, but apparently not?

**Comment by rwjblue** [comment] 2019-05-20 17:40
I created https://github.com/broccolijs/broccoli-source/issues/8 to track fixing this upstream in broccoli-source (IMHO, it should have been **absolutely** safe to do what we are doing here, broccoli-source should expand relative paths for us).

But we should still fix here (along with a test) since updating broccoli-source might take a while to flow downstream...

**Comment by rwjblue** [comment] 2019-05-20 18:01
https://github.com/chadhietala/broccoli-rollup/pull/53 is a failing test case confirming that `this.inputPaths` contains the relative paths

**Comment by krisselden** [comment] 2019-05-21 06:55
@samselikoff you better open your own issue cause @rwjblue PR does not fix your issue but will close this one.

**Comment by samselikoff** [comment] 2019-05-21 12:02
sure thing, thanks!

**Comment by krisselden** [comment] 2019-05-23 21:03
@samselikoff I opened a separate issue for your issue https://github.com/chadhietala/broccoli-rollup/issues/54 and detailed the solution.  I just need to get around to writing a test case for it.  Likely since @Turbo87 is also using the commonjs plugin will also hit that one as well once he gets by this issue.

**Comment by samselikoff** [comment] 2019-05-31 10:46
thx, sorry for not following up :)

**Closed as completed** 2019-06-03 20:55 UTC
