### ISSUE TITLE
Doesn't seem work with rollup-plugin-commonjs

### ISSUE THREAD

**Issue by topaxi** [chadhietala/broccoli-rollup#13] opened 2016-09-25 14:22 UTC
Hi

I'm trying to bundle an app with npm modules, for this I included the rollup-plugin-commonjs. It seems that because of the temporary folder of broccoli it wont find the modules relative to the node module.

Example:

`app/app.js`:

``` js
import P2 from 'p2'
```

`Brocfile.js`:

``` js
module.exports = new Rollup('.', {
  entry: 'app/app.js',
  dest: 'app/app.js',
  format: 'iife',
  plugins: [
    commonjs({
      include: 'node_modules/**'
    }),
    json(),
    nodeResolve({
      jsnext: true,
      browser: true,
      preferBuiltins: false
    })
  }
})
```

Will include the `p2.js` file but not the subsequent files required by `p2.js`.

Using the same configuration on the command-line with `rollup -c` builts the expected output.

After some debugging I found out, that `rollup-plugin-commonjs` tries to match `/home/topaxi/my-project/tmp/rollup-input_base_path-HNZeqlFn.tmp/0/node_modules/p2/src/p2.js` against `/home/topaxi/my-project/node_modules` which obviously won't match.

Should this be supported? Or should I abandon this and just use a `broccoli-funnel` filter to move the module files to be found by rollup?

**Comment by stefanpenner** [comment] 2016-09-25 18:43
This should be supported, it is unclear if the issue is here or in the plugin itself (or both). Will require some further investigation to figure out.

**Comment by cafreeman** [comment] 2017-03-28 19:45
@stefanpenner seeing this in the new GlimmerApp as well. Trying to import Immutable.js and ran into commonjs issues. Attempting to configure like so:

```js
const { GlimmerApp } = require('@glimmer/application-pipeline');
const nodeResolve = require('rollup-plugin-node-resolve');
const commonjs = require('rollup-plugin-commonjs');

module.exports = function(defaults) {
  var app = new GlimmerApp(defaults, {
    // Add options here
    rollup: {
      plugins: [
        commonjs({
          include: 'node_modules/**',
          namedExports: {
            './node_modules/immutable/dist/immutable.js': [ 'Map', 'List', 'Record']
          }
        }),
        nodeResolve({
          jsnext: true,
          browser: true
        })
      ]
    }
  });
```

And getting this error message:
```
The Broccoli Plugin: [RollupWithDependencies] failed with:
Error: 'Record' is not exported by tmp/rollup_with_dependencies-cache_path-v9Ey1EZq.tmp/node_modules/immutable/dist/immutable.js
```

**Comment by BryanCrotaz** [comment] 2017-12-02 13:56
I'm seeing this in a non-Ember project

**Comment by krisselden** [comment] 2019-01-16 00:10
the plugin, does a symlink of input to cachePath/build and symlinks your project node_modules to cachePath/node_modules, so that node module resolution works, this plugin though looks like it requires you to give explicit paths, the path to your symlinked node_modules would be ../node_modules

**Comment by stefanpenner** [comment] 2019-01-16 00:15
@krisselden should this be closed?

**Comment by krisselden** [comment] 2019-05-16 20:28
I'm going to close this as I think I've explained what's wrong (though I haven't tried myself to use this plugin).

**Closed as completed by krisselden** 2019-05-16 20:28 UTC
